image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
   variables:
     GIT_STATEGY: none
   dependencies: maven-build
   script:
    - docker build -t test .


