image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL

stages:
 - package
 - build

maven-build:
  stage: package
  image: maven:3-jdk-8
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build
  variables:
    GIT_STATEGY: none
  dependencies:
  - maven-build
  script:
    - docker build --build-arg BUILD_DATE="$(date)" --build-arg VCS_REF=$CI_BUILD_REF -t $CONTAINER_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CONTAINER_IMAGE:$CI_BUILD_REF_NAME 
