image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
 - package
 - build

maven-build:
  stage: package
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build
  variables:
    GIT_STATEGY: none
  dependencies:
  - maven-build
  script:
    - docker build --build-arg BUILD_DATE="$(date)" --build-arg VCS_REF=$CI_BUILD_REF -t $CI_REGISTRY_IMAGE .


docker-build2:
  stage: build
  variables:
    GIT_STATEGY: none
  script:
    - ls -al target/
    - docker build --build-arg BUILD_DATE="$(date)" --build-arg VCS_REF=$CI_BUILD_REF -t $CI_REGISTRY_IMAGE .


